import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import { Providers } from "./providers";
import { ToastContainer } from "react-toastify";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ổ của Dưa",
  description: "Generated by Thích ăn dưa hấu",
  openGraph: {
    title: "Ổ của Dưa",
    description: "Generated by Thích ăn dưa hấu",
    url: "https://ocuadua.com",
    siteName: "Ổ của Dưa",
    images: [
      {
        url: "https://res.cloudinary.com/dnoecg9cb/image/upload/v1753784173/images/Logo.jpg",
        width: 1200,
        height: 630,
        alt: "Ổ của Dưa",
      },
    ],
    locale: "vi_VN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ổ của Dưa",
    description: "Generated by Thích ăn dưa hấu",
    images: [
      "https://res.cloudinary.com/dnoecg9cb/image/upload/v1753784173/images/Logo.jpg",
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      </head>
      <body>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4321788066240073"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
        <ToastContainer />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
