import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import { Providers } from "./providers";
import { ToastContainer } from "react-toastify";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Script from "next/script";
import { DEFAULT_STATIC_BRAND_IMAGE } from "@/utils/normalizeGithubCdnUrl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  metadataBase: new URL("https://ocuadua.com"),
  title: "Ổ của Dưa",
  description: "Generated by Thích ăn dưa hấu",
  openGraph: {
    title: "Ổ của Dưa",
    description: "Generated by Thích ăn dưa hấu",
    url: "https://ocuadua.com",
    siteName: "Ổ của Dưa",
    images: [
      {
        url: DEFAULT_STATIC_BRAND_IMAGE,
        alt: "Ổ của Dưa",
      },
    ],
    locale: "vi_VN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ổ của Dưa",
    description: "Generated by Thích ăn dưa hấu",
    images: [DEFAULT_STATIC_BRAND_IMAGE],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="9147d08a0630238d1de63a35c74257bc2410b6d1" content="9147d08a0630238d1de63a35c74257bc2410b6d1" />
        <meta name="referrer" content="no-referrer-when-downgrade" />
      </head>
      <body>
        {/* Adsterra Popunder — kích hoạt khi user click đầu tiên */}
        {/*<Script
          src="https://pl29762368.effectivecpmnetwork.com/df/ff/50/dfff50bc2abf5c57568f755f92d85bcd.js"
          strategy="afterInteractive"
        /> */}
        {/* Adsterra Social Bar — widget nổi góc màn hình */}
        {/*<Script
          src="https://pl29762370.effectivecpmnetwork.com/1c/b6/d4/1cb6d46b76a662cb578b8e0eae9e6773.js"
          strategy="afterInteractive"
        />*/}
        {/* Monetag Banner */}
        {/*<Script
          src="//shameful-farm.com/b.XsV-sydOG/lr0EYKWUcu/heJmZ9qulZrUMlckiPSTVcoxgNeDRE/3/NYjqUTtdNFzoEd0/MMTNcN2GOJQR"
          strategy="afterInteractive"
          referrerPolicy="no-referrer-when-downgrade"
        />*/}
        {/* Monetag In-Page Push */}
        <Script
          src="//shameful-farm.com/bjX.Vks/dRGHle0EYHWRcQ/XeZmY9SudZXUOlskFPgTHcsx/NpD_ED3WO/DGEztINpzaEd0dMPTTc/4UNSQj"
          strategy="afterInteractive"
          referrerPolicy="no-referrer-when-downgrade"
        />
        {/* Monetag Video Slider */}
        {/*<Script
          src="//shameful-farm.com/bNXHV.sHdxG/l/0bY/Wtcr/_eBmJ9eusZbUClMksPUTDccx/NODSEU3kO/Tlcyt/Ntz/Ed0DM/ThgEw/MiQY"
          strategy="afterInteractive"
          referrerPolicy="no-referrer-when-downgrade"
        />*/}
        <ToastContainer />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
