import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css';
import { Providers } from './providers';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ổ của Dưa",
  description: "Generated by Hades",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
       <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
